# Test 06 -- GTextField + GTextInput
extends RefCounted

static func run(host: Node) -> bool:
    var TR := load("res://scripts/tests/test_runner.gd")
    var r: RefCounted = TR.new()
    r.init("06_gtext")

    var tf: Variant = ClassDB.instantiate("GTextField")
    host.add_child(tf)
    tf.set_text("FairyGUI")
    r.check(tf.get_text() == "FairyGUI", "text")
    tf.set_text_color(Color.YELLOW)
    r.check(tf.get_text_color() == Color.YELLOW, "text_color")
    tf.set_font_size(17)
    r.check(tf.get_font_size() == 17, "font_size")

    tf.set_ubb_enabled(true)
    tf.set_text("[b]Bold[/b] [url=https://x.com]Link[/url] [img]ui://demo/icon[/img]")
    r.check(tf.get_ubb_link_count() == 1, "ubb links")
    r.check(tf.get_ubb_image_count() == 1, "ubb images")

    var link_href := ""
    tf.fgui_link_click.connect(func(h: String): link_href = h)
    tf.set_rich_text_enabled(true)
    r.check(tf.is_rich_text_enabled(), "rich_text")
    r.check(tf.has_rich_text_label(), "has_label")
    tf.call("_handle_rich_text_meta_clicked", "https://x.com")
    r.check(link_href == "https://x.com", "meta_clicked")
    tf.set_rich_text_enabled(false)

    tf.set_align(1)
    r.check(tf.get_align() == 1, "align")
    tf.set_vertical_align(1)
    r.check(tf.get_vertical_align() == 1, "vertical_align")
    tf.set_single_line(true)
    r.check(tf.is_single_line(), "single_line")
    tf.set_auto_size(1)
    r.check(tf.get_auto_size() == 1, "auto_size")
    tf.set_text("Hello")
    tf.set_font_size(16)
    r.check(tf.get_text_width() > 0, "text_width")
    tf.free()

    var ti: Variant = ClassDB.instantiate("GTextInput")
    host.add_child(ti)
    ti.set_size(Vector2(180, 28))
    r.check(ti.has_native_input(), "has_native_input")
    ti.set_prompt_text("Name")
    r.check(ti.get_prompt_text() == "Name", "prompt")
    ti.set_restrict("0-9")
    ti.set_max_length(3)
    ti.set_text("a12b345")
    r.check(ti.get_text() == "123", "restrict")
    ti.set_display_as_password(true)
    r.check(ti.is_display_as_password(), "password")

    var ct := ""
    ti.fgui_changed.connect(func(v: String): ct = v)
    ti.call("_handle_line_text_changed", "4567")
    r.check(ct == "456", "changed")
    ti.set_selection(1, 1)
    ti.replace_selection("9")
    r.check(ti.get_text() == "496", "replace_selection")

    ti.set_hide_input(true)
    r.check(ti.is_hide_input(), "hide_input")
    ti.set_keyboard_input(false)
    r.check(not ti.is_keyboard_input(), "keyboard_input")
    ti.set_disable_ime(true)
    r.check(ti.is_disable_ime(), "disable_ime")
    ti.set_mouse_wheel_enabled(false)
    r.check(not ti.is_mouse_wheel_enabled(), "mouse_wheel")
    ti.set_multiline(true)
    r.check(ti.is_multiline(), "multiline")
    ti.set_multiline(false)

    ti.free()
    return r.finalize()
